/**
 * Full Exercise Catalog — ATR Categorized
 * Run: npx tsx prisma/seed-exercises.ts
 *
 * Covers all 3 ATR phases:
 * - Acumulación: compound (fuerza base, hipertrofia)
 * - Transformación: olympic + ballistic + plyometric_low + contrast
 * - Realización: plyometric_high + transfer (beach volleyball specific)
 */

import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const exercises = [
    // ────────────────────────────────────────────────────────────
    // ACUMULACIÓN — Compound (fuerza máxima e hipertrofia)
    // ────────────────────────────────────────────────────────────
    {
        name: 'Sentadilla con Barra',
        nameEn: 'Back Squat',
        muscleGroups: JSON.stringify(['quadriceps', 'glutes', 'hamstrings', 'core', 'erector_spinae']),
        equipment: 'barbell',
        difficulty: 'intermediate',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation', 'transformation']),
        impactLevel: 'none',
        contrastPairName: 'Salto Vertical con Contramovement (CMJ)',
        imageUrl: '/exercises/squat.jpg',
        sportSpecific: false,
        cues: 'Pies al ancho de hombros, rodillas sobre dedos, pecho erguido, descender hasta paralelo o más, conducir desde los talones al subir.',
        description: 'Ejercicio rey de la fuerza máxima del tren inferior. Base fundamental de la fase de Acumulación.',
    },
    {
        name: 'Sentadilla Frontal',
        nameEn: 'Front Squat',
        muscleGroups: JSON.stringify(['quadriceps', 'glutes', 'core', 'upper_back']),
        equipment: 'barbell',
        difficulty: 'advanced',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Barra sobre deltoides frontales, codos altos, torso vertical. Mayor reclutamiento de cuádriceps y core que la sentadilla trasera.',
        description: 'Variante de sentadilla con mayor demanda de core y cuádriceps. Excelente para posición de recepción de cargada olímpica.',
    },
    {
        name: 'Peso Muerto Convencional',
        nameEn: 'Conventional Deadlift',
        muscleGroups: JSON.stringify(['hamstrings', 'glutes', 'erector_spinae', 'lats', 'traps', 'forearms']),
        equipment: 'barbell',
        difficulty: 'intermediate',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation', 'transformation']),
        impactLevel: 'none',
        contrastPairName: 'Swing con Kettlebell',
        imageUrl: '/exercises/deadlift.jpg',
        sportSpecific: false,
        cues: 'Cadera alta, columna neutra, barra rozando piernas al subir. Empujar el suelo hacia abajo, no tirar hacia arriba.',
        description: 'Desarrolla la cadena posterior completa. Clave para la potencia de salto en voleibol de playa.',
    },
    {
        name: 'Peso Muerto Rumano',
        nameEn: 'Romanian Deadlift',
        muscleGroups: JSON.stringify(['hamstrings', 'glutes', 'erector_spinae']),
        equipment: 'barbell',
        difficulty: 'intermediate',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation']),
        impactLevel: 'none',
        imageUrl: '/exercises/rdl.jpg',
        sportSpecific: false,
        cues: 'Caderas hacia atrás, rodillas levemente flexionadas, columna neutra durante todo el movimiento. Sentir el estiramiento del isquiotibial.',
        description: 'Énfasis en isquiotibiales y glúteos. Fundamental para desarrollar la extensión de cadera potente del salto.',
    },
    {
        name: 'Hip Thrust con Barra',
        nameEn: 'Barbell Hip Thrust',
        muscleGroups: JSON.stringify(['glutes', 'hamstrings', 'core']),
        equipment: 'barbell',
        difficulty: 'intermediate',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation', 'transformation']),
        impactLevel: 'none',
        contrastPairName: 'Multisaltos Horizontales (Bounding)',
        imageUrl: '/exercises/hip_thrust.jpg',
        sportSpecific: false,
        cues: 'Parte superior de la espalda sobre el banco, barra en la cadera. Empujar hasta extensión completa de cadera. Contraer glúteos en la cima.',
        description: 'Máxima activación de glúteo mayor. Directamente vinculado a la potencia de despegue vertical.',
    },
    {
        name: 'Sentadilla Búlgara',
        nameEn: 'Bulgarian Split Squat',
        muscleGroups: JSON.stringify(['quadriceps', 'glutes', 'hamstrings', 'hip_flexors']),
        equipment: 'dumbbell',
        difficulty: 'intermediate',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation']),
        impactLevel: 'none',
        imageUrl: '/exercises/bulgarian_squat.jpg',
        sportSpecific: false,
        cues: 'Pie trasero elevado, rodilla delantera sobre el tobillo. Trabajar un rango de movimiento completo.',
        description: 'Trabajo unilateral de piernas. Corrige desequilibrios y mejora la estabilidad en el salto a una pierna.',
    },
    {
        name: 'Press de Banca',
        nameEn: 'Bench Press',
        muscleGroups: JSON.stringify(['pectorals', 'triceps', 'anterior_deltoid']),
        equipment: 'barbell',
        difficulty: 'beginner',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation', 'transformation']),
        impactLevel: 'none',
        contrastPairName: 'Lanzamiento Balón Medicinal (Chest Pass)',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Agarre al ancho de hombros, omóplatos retraídos y deprimidos, descender la barra al esternón inferior, empujar verticalmente.',
        description: 'Fuerza máxima de empuje de tren superior. Potencia transferida al saque y remate en voleibol.',
    },
    {
        name: 'Press Militar',
        nameEn: 'Standing Overhead Press',
        muscleGroups: JSON.stringify(['deltoids', 'triceps', 'upper_traps', 'core']),
        equipment: 'barbell',
        difficulty: 'intermediate',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation', 'transformation']),
        impactLevel: 'none',
        contrastPairName: 'Lanzamiento Balón Medicinal (Overhead)',
        imageUrl: '/exercises/overhead_press.jpg',
        sportSpecific: false,
        cues: 'De pie, barra desde clavículas, presionar hacia arriba y ligeramente atrás, core tensionado. No hiperextender lumbar.',
        description: 'Fuerza máxima overhead. Directamente transferible al remate y saque en voleibol de playa.',
    },
    {
        name: 'Remo con Barra',
        nameEn: 'Barbell Row',
        muscleGroups: JSON.stringify(['lats', 'rhomboids', 'rear_deltoid', 'biceps', 'erector_spinae']),
        equipment: 'barbell',
        difficulty: 'intermediate',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Torso a 45°, barra hacia el ombligo, codos cerca al cuerpo. Retraer la escápula al final del movimiento.',
        description: 'Fuerza de tracción horizontal. Equilibra el trabajo de empuje del press. Fundamental para la salud de hombros en deportes overhead.',
    },
    {
        name: 'Dominadas',
        nameEn: 'Pull-ups',
        muscleGroups: JSON.stringify(['lats', 'biceps', 'rhomboids', 'core']),
        equipment: 'bodyweight',
        difficulty: 'intermediate',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Agarre prono al ancho de hombros. Iniciar el movimiento con la depresión escapular, luego el codo. Subir hasta barbilla sobre la barra.',
        description: 'Tracción vertical de tren superior. Relación fuerza/peso corporal clave para la potencia de salto en voleibol.',
    },
    {
        name: 'Prensa de Piernas',
        nameEn: 'Leg Press',
        muscleGroups: JSON.stringify(['quadriceps', 'glutes', 'hamstrings']),
        equipment: 'machine',
        difficulty: 'beginner',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Pies al ancho de hombros en plataforma. No bloquear rodillas al extender. Rango de movimiento completo.',
        description: 'Sobrecarga de tren inferior sin demanda de core. Útil en semanas de alta fatiga durante Acumulación.',
    },
    {
        name: 'Zancada con Mancuernas',
        nameEn: 'Dumbbell Lunge',
        muscleGroups: JSON.stringify(['quadriceps', 'glutes', 'hamstrings', 'calves']),
        equipment: 'dumbbell',
        difficulty: 'beginner',
        exerciseType: 'compound',
        atrPhases: JSON.stringify(['accumulation']),
        impactLevel: 'low',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Paso amplio, rodilla delantera sobre tobillo, torso erguido. Empujar desde el talón delantero para volver.',
        description: 'Trabajo unilateral de tren inferior. Mejora la estabilidad y equilibrio.',
    },

    // ────────────────────────────────────────────────────────────
    // TRANSFORMACIÓN — Olympic Lifts (levantamientos olímpicos)
    // ────────────────────────────────────────────────────────────
    {
        name: 'Colgada de Potencia (Hang Clean)',
        nameEn: 'Hang Power Clean',
        muscleGroups: JSON.stringify(['glutes', 'hamstrings', 'traps', 'deltoids', 'quadriceps', 'core']),
        equipment: 'barbell',
        difficulty: 'advanced',
        exerciseType: 'olympic',
        atrPhases: JSON.stringify(['transformation', 'realization']),
        impactLevel: 'low',
        imageUrl: '/exercises/hang_clean.jpg',
        sportSpecific: true,
        cues: 'Posición de colgada (rodillas-cadera), triple extensión explosiva (tobillo-rodilla-cadera), encogimiento de hombros y recepción en cuarto sentadilla. Fuerza reactiva del piso.',
        description: 'Levantamiento olímpico desde posición de colgada. Desarrolla la potencia de cadena posterior completa. Ideal para Transformación.',
    },
    {
        name: 'Cargada de Potencia (Power Clean)',
        nameEn: 'Power Clean',
        muscleGroups: JSON.stringify(['glutes', 'hamstrings', 'traps', 'deltoids', 'quadriceps', 'core', 'forearms']),
        equipment: 'barbell',
        difficulty: 'advanced',
        exerciseType: 'olympic',
        atrPhases: JSON.stringify(['transformation', 'realization']),
        impactLevel: 'low',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Jalón inicial desde el suelo con espalda plana, primer tirón controlado hasta rodillas, segundo tirón explosivo con triple extensión, recepción en rack position.',
        description: 'Variante del levantamiento olímpico. Desarrolla potencia de cadena posterior completa desde el suelo.',
    },
    {
        name: 'Push Press',
        nameEn: 'Push Press',
        muscleGroups: JSON.stringify(['deltoids', 'triceps', 'quadriceps', 'glutes', 'core']),
        equipment: 'barbell',
        difficulty: 'intermediate',
        exerciseType: 'ballistic',
        atrPhases: JSON.stringify(['transformation', 'realization']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Pequeño dip de rodillas (10-15°), extensión explosiva de piernas que transfiere fuerza a la barra, presionar sobre cabeza. Coordinar empuje de piernas y brazos.',
        description: 'Ejercicio de potencia balistico overhead. La inercia de las piernas permite manejar más carga que el press estricto. Transferencia directa al remate.',
    },
    {
        name: 'Jalón de Potencia (High Pull)',
        nameEn: 'Barbell High Pull',
        muscleGroups: JSON.stringify(['traps', 'deltoids', 'glutes', 'hamstrings', 'quadriceps']),
        equipment: 'barbell',
        difficulty: 'intermediate',
        exerciseType: 'olympic',
        atrPhases: JSON.stringify(['transformation']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Triple extensión explosiva desde colgada, jalón de codos hacia arriba y afuera hasta altura de pecho. No requiere recepción.',
        description: 'Simplificación del Clean que desarrolla potencia de cadena posterior y trapecios. Apropiado como introducción a los levantamientos olímpicos.',
    },
    {
        name: 'Arranque de Fuerza (Snatch Pull)',
        nameEn: 'Snatch Pull',
        muscleGroups: JSON.stringify(['glutes', 'hamstrings', 'traps', 'core', 'lats']),
        equipment: 'barbell',
        difficulty: 'advanced',
        exerciseType: 'olympic',
        atrPhases: JSON.stringify(['transformation', 'realization']),
        impactLevel: 'low',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Agarre amplio de arranque, mismo patrón que el Clean pero con mayor apertura de brazos. Triple extensión y jalón alto.',
        description: 'Desarrolla potencia de cadena posterior con énfasis en la velocidad de jalón. Precursor del arranque completo.',
    },
    {
        name: 'Swing con Kettlebell',
        nameEn: 'Kettlebell Swing',
        muscleGroups: JSON.stringify(['glutes', 'hamstrings', 'core', 'lats', 'deltoids']),
        equipment: 'kettlebell',
        difficulty: 'intermediate',
        exerciseType: 'ballistic',
        atrPhases: JSON.stringify(['transformation']),
        impactLevel: 'low',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Bisagra de cadera, proyectar la kettlebell con la extensión explosiva de cadera, absorber en la bajada. El swing es un movimiento de cadera, no de brazos.',
        description: 'Enseña la extensión explosiva de cadera. Excelente introducción a los patrones de potencia balística.',
    },

    // ────────────────────────────────────────────────────────────
    // TRANSFORMACIÓN — Pliometría Low Impact
    // ────────────────────────────────────────────────────────────
    {
        name: 'Salto al Cajón (Box Jump)',
        nameEn: 'Box Jump',
        muscleGroups: JSON.stringify(['quadriceps', 'glutes', 'calves', 'core']),
        equipment: 'box',
        difficulty: 'intermediate',
        exerciseType: 'plyometric_low',
        atrPhases: JSON.stringify(['transformation']),
        impactLevel: 'medium',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Saltar con contra-movimiento, aterrizar suavemente con ambos pies sobre el cajón, rodillas flexionadas. Bajar caminando (no saltando) para reducir el impacto acumulado.',
        description: 'Pliometría de bajo-medio impacto. El cajón elimina el aterrizaje con carga excéntrica alta del salto libre. Ideal para Transformación.',
    },
    {
        name: 'Salto Vertical con Contramovement (CMJ)',
        nameEn: 'Countermovement Jump',
        muscleGroups: JSON.stringify(['quadriceps', 'glutes', 'hamstrings', 'calves', 'core']),
        equipment: 'bodyweight',
        difficulty: 'beginner',
        exerciseType: 'plyometric_low',
        atrPhases: JSON.stringify(['transformation', 'realization']),
        impactLevel: 'medium',
        imageUrl: '/exercises/cmj.jpg',
        sportSpecific: true,
        cues: 'Descenso rápido y controlado (contra-movimiento), cambio de dirección explosivo en el fondo, extensión máxima de tobillo-rodilla-cadera, brazos hacia arriba. Aterrizaje suave en punta-talón.',
        description: 'El salto más específico del voleibol de playa. Indicador de potencia de piernas y base de todos los saltos del juego.',
    },
    {
        name: 'Squat Jump (sin contramovimiento)',
        nameEn: 'Squat Jump',
        muscleGroups: JSON.stringify(['quadriceps', 'glutes', 'calves']),
        equipment: 'bodyweight',
        difficulty: 'beginner',
        exerciseType: 'plyometric_low',
        atrPhases: JSON.stringify(['transformation']),
        impactLevel: 'low',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Descender a posición de media sentadilla, pausa 2 segundos, luego saltar con máxima potencia. Al no haber contra-movimiento, se entrena la fuerza concéntrica pura.',
        description: 'Pliometría sin ciclo de estiramiento-acortamiento. Entrena la fuerza concéntrica del salto. Menor impacto que el CMJ.',
    },
    {
        name: 'Saltos Continuos sobre Vallas',
        nameEn: 'Continuous Hurdle Hops',
        muscleGroups: JSON.stringify(['calves', 'quadriceps', 'glutes', 'core']),
        equipment: 'box',
        difficulty: 'intermediate',
        exerciseType: 'plyometric_low',
        atrPhases: JSON.stringify(['transformation']),
        impactLevel: 'medium',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Saltar sobre vallas bajas (15-30cm) de forma continua y rítmica. Minimizar tiempo de contacto en suelo. Brazos coordinar con el salto.',
        description: 'Desarrolla la coordinación y el ritmo pliométrico. Introducción al ciclo de estiramiento-acortamiento.',
    },
    {
        name: 'Salto con Mancuernas (Dumbbell Jump Squat)',
        nameEn: 'Weighted Jump Squat',
        muscleGroups: JSON.stringify(['quadriceps', 'glutes', 'hamstrings', 'calves']),
        equipment: 'dumbbell',
        difficulty: 'intermediate',
        exerciseType: 'plyometric_low',
        atrPhases: JSON.stringify(['transformation']),
        impactLevel: 'medium',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Mancuernas ligeras (10-20% del peso corporal). Contra-movimiento y salto máximo. Aterrizaje controlado. No sobrecargar: la carga extra no debe superar el 30% del peso corporal.',
        description: 'Salto con carga adicional leve. Desarrolla la relación fuerza-velocidad con resistencia.',
    },

    // ────────────────────────────────────────────────────────────
    // TRANSFORMACIÓN — Balísticos (Cont)
    // ────────────────────────────────────────────────────────────
    {
        name: 'Lanzamiento Balón Medicinal (Chest Pass)',
        nameEn: 'Medicine Ball Chest Pass Throw',
        muscleGroups: JSON.stringify(['pectorals', 'triceps', 'deltoids', 'core']),
        equipment: 'medicine_ball',
        difficulty: 'beginner',
        exerciseType: 'ballistic',
        atrPhases: JSON.stringify(['transformation', 'realization']),
        impactLevel: 'none',
        contrastPairName: null,
        imageUrl: null,
        sportSpecific: true,
        cues: 'Contra pared o con compañero. Balón 3-5 kg. Extensión explosiva de brazos desde el pecho. NO retener el balón: lanzamiento completo.',
        description: 'Transferencia de potencia de tren superior. Simula la velocidad del remate de voleibol. Usar con método de contrastes tras el press de banca.',
    },
    {
        name: 'Lanzamiento Balón Medicinal (Overhead)',
        nameEn: 'Medicine Ball Overhead Throw',
        muscleGroups: JSON.stringify(['deltoids', 'triceps', 'lats', 'core', 'quadriceps']),
        equipment: 'medicine_ball',
        difficulty: 'intermediate',
        exerciseType: 'ballistic',
        atrPhases: JSON.stringify(['transformation', 'realization']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Balón sobre la cabeza, ligera flexión de rodillas, lanzar explosivamente hacia adelante. Coordinar extensión de todo el cuerpo.',
        description: 'Imita el patrón de movimiento del remate y saque. Excelente con método de contrastes tras el press militar.',
    },
    {
        name: 'Lanzamiento Balón Medicinal (Rotacional)',
        nameEn: 'Medicine Ball Rotational Throw',
        muscleGroups: JSON.stringify(['obliques', 'core', 'hips', 'deltoids']),
        equipment: 'medicine_ball',
        difficulty: 'intermediate',
        exerciseType: 'ballistic',
        atrPhases: JSON.stringify(['transformation', 'realization']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: true,
        cues: 'De pie lateral a la pared, rotar explosivamente desde cadera+tronco para lanzar. El poder viene de la rotación de cadera, no solo de los brazos.',
        description: 'Desarrolla la potencia rotacional. Específico para el remate en voleibol que requiere rotación de tronco.',
    },

    // ────────────────────────────────────────────────────────────
    // REALIZACIÓN — Pliometría High Impact (fuerza reactiva)
    // ────────────────────────────────────────────────────────────
    {
        name: 'Drop Jump (DJ)',
        nameEn: 'Drop Jump',
        muscleGroups: JSON.stringify(['calves', 'quadriceps', 'glutes', 'hamstrings', 'tibialis_anterior']),
        equipment: 'box',
        difficulty: 'advanced',
        exerciseType: 'plyometric_high',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'high',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Cajón 20-40cm. Dejarse caer (no saltar), contacto en punta de pies, MÍNIMO tiempo de contacto (<250ms ideal), rebotar lo más alto posible. Medir índice de fuerza reactiva = alt/tiempo contacto.',
        description: 'El ejercicio de pliometría reactiva de alto impacto por excelencia. Entrena el ciclo de estiramiento-acortamiento (CEA) rápido. Análogo al impacto del aterrizaje y despegue en voleibol.',
    },
    {
        name: 'Multisaltos con Desplazamiento (Bounding)',
        nameEn: 'Bounding',
        muscleGroups: JSON.stringify(['glutes', 'hamstrings', 'calves', 'quadriceps', 'hip_flexors']),
        equipment: 'bodyweight',
        difficulty: 'advanced',
        exerciseType: 'plyometric_high',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'high',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Saltos alternados de pierna maximizando longitud y altura. Ciclo CEA en cada aterrizaje. Brazos en oposición. Medir distancia total de la tanda.',
        description: 'Multisaltos horizontales que desarrollan la fuerza reactiva de locomoción. Específico para los desplazamientos explosivos en arena.',
    },
    {
        name: 'Salto a Una Pierna (Single-Leg Hop)',
        nameEn: 'Single-Leg Hop',
        muscleGroups: JSON.stringify(['glutes', 'quadriceps', 'calves', 'hamstrings', 'ankle_stabilizers']),
        equipment: 'bodyweight',
        difficulty: 'advanced',
        exerciseType: 'plyometric_high',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'high',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Saltar y aterrizar en la misma pierna. Mínimo tiempo de contacto. Progresar: horizontal → vertical → lateral → en serie (triple hop).',
        description: 'Desarrolla la fuerza reactiva unilateral. Simula los saltos de defensa y remate en situaciones de desequilibrio en arena.',
    },
    {
        name: 'Lagartijas Pliométricas (con aplauso)',
        nameEn: 'Plyometric Push-ups',
        muscleGroups: JSON.stringify(['pectorals', 'triceps', 'anterior_deltoid', 'core']),
        equipment: 'bodyweight',
        difficulty: 'advanced',
        exerciseType: 'plyometric_high',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'medium',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Descender rápido, empujar explosivamente para despegar del suelo y aplaudir. Aterrizar con los brazos ligeramente flexionados. Mantener el cuerpo rígido.',
        description: 'Pliometría de tren superior. Desarrolla la potencia explosiva de empuje, transferible al golpe de ataque en voleibol.',
    },
    {
        name: 'Depth Drop (caída de cajón, sin rebotar)',
        nameEn: 'Depth Drop',
        muscleGroups: JSON.stringify(['quadriceps', 'glutes', 'hamstrings', 'calves', 'ankle_stabilizers']),
        equipment: 'box',
        difficulty: 'advanced',
        exerciseType: 'plyometric_high',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'high',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Caída desde el cajón, aterrizar con amortiguación controlada absorbiendo el impacto. Objetivo: entrenamiento de la fase excéntrica de alta velocidad. No saltar.',
        description: 'Entrena la capacidad de absorción de fuerza y la resistencia tendinosa. Prerrequisito antes de los Drop Jumps.',
    },
    {
        name: 'Salto Lateral Reactivo (Side-to-Side)',
        nameEn: 'Lateral Reactive Jump',
        muscleGroups: JSON.stringify(['glutes', 'hip_abductors', 'calves', 'quadriceps', 'ankles']),
        equipment: 'bodyweight',
        difficulty: 'intermediate',
        exerciseType: 'plyometric_high',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'high',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Saltos laterales rápidos sobre una línea. Mínimo tiempo de contacto. Mantener caderas bajas. Simular el movimiento lateral de defensa en arena.',
        description: 'Desarrolla la potencia lateral reactiva. Específico para los desplazamientos defensivos y el posicionamiento en voleibol de playa.',
    },

    // ────────────────────────────────────────────────────────────
    // REALIZACIÓN — Transferencia Específica Beach Volleyball
    // ────────────────────────────────────────────────────────────
    {
        name: 'Remate con Chaleco Lastrado',
        nameEn: 'Weighted Spike Jump',
        muscleGroups: JSON.stringify(['glutes', 'quadriceps', 'calves', 'deltoids', 'core', 'wrist_extensors']),
        equipment: 'band',
        difficulty: 'advanced',
        exerciseType: 'transfer',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'medium',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Chaleco 3-5% peso corporal. Aproximación al remate, salto, golpe aéreo a máxima velocidad. Mantener la técnica del remate competitivo. Velocidad de ejecución máxima.',
        description: 'Transferencia directa al remate. La resistencia ligera del chaleco obliga a reclutar más unidades motoras, mejorando la potencia de ataque.',
    },
    {
        name: 'Bloqueo con Banda Elástica',
        nameEn: 'Band-Resisted Block Jump',
        muscleGroups: JSON.stringify(['quadriceps', 'deltoids', 'triceps', 'core', 'calves']),
        equipment: 'band',
        difficulty: 'intermediate',
        exerciseType: 'transfer',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'medium',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Banda elástica media anclada al suelo o en cintura. Simular el salto de bloqueo con extensión completa de brazos sobre la cabeza. Máxima velocidad de despegue.',
        description: 'Simula el bloqueo en red. La banda genera resistencia en la dirección del salto, potenciando la fuerza explosiva vertical específica del bloqueo.',
    },
    {
        name: 'Defensa Reactiva en Arena',
        nameEn: 'Reactive Dive Defense Drill',
        muscleGroups: JSON.stringify(['glutes', 'hip_abductors', 'core', 'quadriceps', 'hamstrings']),
        equipment: 'band',
        difficulty: 'advanced',
        exerciseType: 'transfer',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'medium',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Partir de posición defensiva. Ante señal, desplazarse lateralmente 2-3m y realizar la técnica defensiva (mancheta o toque de control). Máxima velocidad de reacción.',
        description: 'Transferencia al movimiento defensivo. Combina reacción, desplazamiento lateral y técnica defensiva a velocidad competitiva.',
    },
    {
        name: 'Salto de Bloqueo Reactivo',
        nameEn: 'Reactive Block with Visual Cue',
        muscleGroups: JSON.stringify(['quadriceps', 'glutes', 'calves', 'deltoids', 'core']),
        equipment: 'bodyweight',
        difficulty: 'advanced',
        exerciseType: 'transfer',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'high',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Compañero o entrenador señala dirección. Reaccionar y saltar en bloqueo. Entrenar: lectura → desplazamiento lateral → salto → brazo sobre la red. Simula la toma de decisión competitiva.',
        description: 'Bloqueo con señal visual reactiva. Desarrolla la potencia de bloqueo + tiempo de reacción. Pico de transferencia pre-competencia.',
    },
    {
        name: 'Saque con Chaleco Lastrado',
        nameEn: 'Weighted Serve',
        muscleGroups: JSON.stringify(['deltoids', 'core', 'triceps', 'obliques', 'hip_flexors']),
        equipment: 'band',
        difficulty: 'intermediate',
        exerciseType: 'transfer',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'low',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Chaleco muy ligero (2-4% PC). Patrón completo del saque competitivo. La carga extra no debe alterar la técnica.',
        description: 'Potencia el saque mejorando la fuerza de empuje overhead con la biomecánica exacta del saque.',
    },
    {
        name: 'Desplazamiento Lateral con Banda + Salto',
        nameEn: 'Lateral Band Sprint + Jump',
        muscleGroups: JSON.stringify(['hip_abductors', 'glutes', 'quadriceps', 'calves']),
        equipment: 'band',
        difficulty: 'advanced',
        exerciseType: 'transfer',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'medium',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Banda lateral resistida. Sprint lateral 2-3m, luego salto vertical máximo. Simula los cambios de dirección + despegue vertical del juego real.',
        description: 'Combina desplazamiento lateral con salto vertical. Simula el cambio de dirección → salto de bloqueo/remate del voleibol de playa.',
    },
    {
        name: 'Ataque con Banda Elástica (simulación)',
        nameEn: 'Attack Rotation with Band',
        muscleGroups: JSON.stringify(['obliques', 'core', 'deltoids', 'pectorals', 'forearm']),
        equipment: 'band',
        difficulty: 'intermediate',
        exerciseType: 'transfer',
        atrPhases: JSON.stringify(['realization']),
        impactLevel: 'low',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Banda anclada a la red/poste. Simular la rotación del remate con resistencia. Explosión máxima en el punto de contacto imaginario.',
        description: 'Entrena la rotación de tronco del remate contra resistencia progresiva. Aumenta la velocidad del golpe.',
    },

    // ────────────────────────────────────────────────────────────
    // ACCESORIOS (todas las fases — volumen bajo)
    // ────────────────────────────────────────────────────────────
    {
        name: 'Elevación Lateral de Hombros',
        nameEn: 'Lateral Raise',
        muscleGroups: JSON.stringify(['medial_deltoid', 'supraspinatus']),
        equipment: 'dumbbell',
        difficulty: 'beginner',
        exerciseType: 'accessory',
        atrPhases: JSON.stringify(['accumulation']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Elevar mancuernas lateralmente hasta la horizontal. Sin impulso. Control total en la fase excéntrica.',
        description: 'Fortalece el deltoides medial. Apoya la estabilidad de hombro en gestos overhead del voleibol.',
    },
    {
        name: 'Face Pull con Cable',
        nameEn: 'Face Pull',
        muscleGroups: JSON.stringify(['rear_deltoid', 'rhomboids', 'rotator_cuff', 'traps']),
        equipment: 'cable',
        difficulty: 'beginner',
        exerciseType: 'accessory',
        atrPhases: JSON.stringify(['accumulation']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Cuerda al nivel de los ojos, tirar hacia la cara rotando externamente los hombros. Los codos terminan por encima de las manos.',
        description: 'Trabajo de manguito rotador y deltoides posterior. Clave para la salud de hombros en deportes overhead como el voleibol.',
    },
    {
        name: 'Elevación de Pantorrillas de Pie',
        nameEn: 'Standing Calf Raise',
        muscleGroups: JSON.stringify(['gastrocnemius', 'soleus']),
        equipment: 'machine',
        difficulty: 'beginner',
        exerciseType: 'accessory',
        atrPhases: JSON.stringify(['accumulation']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: true,
        cues: 'Rango de movimiento completo. Pausa de 2 segundos en la cima. Control en la bajada. No rebotar en el fondo.',
        description: 'Fortalece la pantorrilla. Fundamental para el despegue de tobillo en todos los saltos del voleibol.',
    },
    {
        name: 'Curl de Isquiotibiales Acostado',
        nameEn: 'Lying Leg Curl',
        muscleGroups: JSON.stringify(['hamstrings', 'calves']),
        equipment: 'machine',
        difficulty: 'beginner',
        exerciseType: 'accessory',
        atrPhases: JSON.stringify(['accumulation']),
        impactLevel: 'none',
        imageUrl: null,
        sportSpecific: false,
        cues: 'Control en la fase excéntrica. No usar impulso. Contracción máxima al final del movimiento.',
        description: 'Trabajo aislado de isquiotibiales. Complementa los movimientos compuestos de la Acumulación.',
    },
];

async function main() {
    console.log(`\n🏋️  Seeding ATR exercise catalog (${exercises.length} exercises)...\n`);

    let created = 0;
    let updated = 0;

    for (const ex of exercises) {
        const result = await prisma.exercise.upsert({
            where: { name: ex.name },
            update: {
                nameEn: ex.nameEn,
                muscleGroups: ex.muscleGroups,
                equipment: ex.equipment,
                difficulty: ex.difficulty,
                exerciseType: ex.exerciseType,
                atrPhases: ex.atrPhases,
                impactLevel: ex.impactLevel,
                contrastPairName: ex.contrastPairName ?? null,
                imageUrl: ex.imageUrl ?? null,
                sportSpecific: ex.sportSpecific,
                cues: ex.cues,
                description: ex.description,
            },
            create: {
                name: ex.name,
                nameEn: ex.nameEn,
                muscleGroups: ex.muscleGroups,
                equipment: ex.equipment,
                difficulty: ex.difficulty,
                exerciseType: ex.exerciseType,
                atrPhases: ex.atrPhases,
                impactLevel: ex.impactLevel,
                contrastPairName: ex.contrastPairName ?? null,
                imageUrl: ex.imageUrl ?? null,
                sportSpecific: ex.sportSpecific,
                cues: ex.cues,
                description: ex.description,
            },
        });
        console.log(`  ${result.name}`);
        created++;
    }

    // Summary by phase
    const byPhase: Record<string, number> = { accumulation: 0, transformation: 0, realization: 0 };
    const byType: Record<string, number> = {};

    for (const ex of exercises) {
        const phases = JSON.parse(ex.atrPhases) as string[];
        for (const p of phases) byPhase[p] = (byPhase[p] || 0) + 1;
        byType[ex.exerciseType] = (byType[ex.exerciseType] || 0) + 1;
    }

    console.log(`\n✅ ${created} exercises seeded!\n`);
    console.log('📊 By ATR Phase:');
    for (const [k, v] of Object.entries(byPhase)) console.log(`   ${k}: ${v}`);
    console.log('\n🏷️  By Type:');
    for (const [k, v] of Object.entries(byType)) console.log(`   ${k}: ${v}`);
}

main()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
